---
kind: pipeline
name: linux-amd64

platform:
  arch: amd64
  os: linux

steps:
- name: build
  image: plugins/docker
  settings:
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
    dockerfile: Dockerfile
    repo: ${DRONE_REPO_OWNER}/${DRONE_REPO_NAME}
    tags:
      - ${DRONE_BUILD_NUMBER}-${DRONE_COMMIT_SHA:0:7}-${DRONE_STAGE_ARCH}

---
kind: pipeline
name: linux-arm64

platform:
  arch: arm64
  os: linux

steps:
- name: build
  image: plugins/docker
  settings:
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
    dockerfile: Dockerfile
    repo: ${DRONE_REPO_OWNER}/${DRONE_REPO_NAME}
    tags:
      - ${DRONE_BUILD_NUMBER}-${DRONE_COMMIT_SHA:0:7}-${DRONE_STAGE_ARCH}

---
kind: pipeline
name: linux-arm

platform:
  arch: arm
  os: linux

steps:
- name: build
  image: plugins/docker
  settings:
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
    dockerfile: Dockerfile
    repo: ${DRONE_REPO_OWNER}/${DRONE_REPO_NAME}
    tags:
      - ${DRONE_BUILD_NUMBER}-${DRONE_COMMIT_SHA:0:7}-${DRONE_STAGE_ARCH}

---
kind: pipeline
name: manifest

steps:
- name: latest
  image: plugins/manifest
  pull: always
  settings:
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
    target: ${DRONE_REPO_OWNER}/${DRONE_REPO_NAME}:latest
    template: ${DRONE_REPO_OWNER}/${DRONE_REPO_NAME}:${DRONE_BUILD_NUMBER}-${DRONE_COMMIT_SHA:0:7}-ARCH
    platforms:
      - linux/amd64
      - linux/arm
      - linux/arm64

depends_on:
  - linux-amd64
  - linux-arm64
  - linux-arm
